### ISSUE TITLE
v2.0 roadmap

### ISSUE THREAD

**Issue by palkan** [palkan/anyway_config#32]
Most of functionality has been covered by #24 and released as `2.0.0.pre`.

The goal of v2.0 is to refactor the codebase (make it more _maintainable_) and add a bunch of new features:
- [x] Introduce better code style rules (added [`standard`](https://github.com/testdouble/standard))
- [x] Split God-like `Config` class into modules
- [x] Fix configs inheritance
- [x] Improve naming inference to support `<Some>Config` (for app-level configs)
- [x] Refactor sources mechanism and introduce _loaders_ API (https://github.com/palkan/anyway_config/pull/46)
- [x] Replace `Config.new(overrides: data)` with `Config.new(data)` (**breaking**)
- [x] Better Rails integration (global config, `app/configs` support)
- [x] **Credentials** support (with per-env creds)
- [x] `*.yml.local` and `.enc.local` support
- [x] Source tracing (which source did this value come from?) (#53)
- [x] Testing utils (`with_env({key => val}){ ... }`)
- [x] Add Rails generator `rails g config name key,key2,key3` (https://github.com/palkan/anyway_config/pull/52)
- [x] Required parameters validation (https://github.com/palkan/anyway_config/pull/50)
- [x] Validate usage of reserved attribute names (https://github.com/palkan/anyway_config/pull/50)

Minor TODOs:

- [x] Support source tracing in OptParser
- [x] Add `#deconstruct_keys`
- [x] Add `on_load` hook
